"""
Findings Resource
=================

Falcon resource for reading and reviewing analysis findings. Findings are
generated by automated analysis pipelines and can be reviewed (approved /
annotated) by clinicians through the ``POST`` endpoint.

Routes
------
* ``GET  /findings``              -- list / filter findings.
* ``GET  /findings/{entity_id}``  -- retrieve a single finding.
* ``POST /findings/{entity_id}``  -- review (approve / annotate) a finding.
"""

import logging

import falcon

from api.resources.BaseResource import BaseResource
from api.util.VidioException import DBException


class FindingsResource(BaseResource):
    """Falcon resource for the ``/findings`` endpoint family.

    Unlike most other resources, findings are **not** created directly
    through the API -- they are produced by analysis pipelines.  The
    ``POST`` endpoint is used exclusively for *reviewing* an existing
    finding (setting the ``reviewed`` flag, adding notes, etc.).

    Inherits shared helpers from :class:`~api.resources.BaseResource.BaseResource`.
    """

    def on_get(self, req, resp):
        """Handle ``GET /findings`` -- list or filter findings.

        Parameters
        ----------
        req : falcon.Request
            May contain ``?filter={...}`` with a JSON-encoded filter.
        resp : falcon.Response
            On success, ``resp.media`` is a list of finding dicts.

        Response Codes
        --------------
        * **200** -- findings retrieved.
        * **500** -- unexpected server error.
        """
        log = logging.getLogger(__name__)
        try:
            flt = self.load_filter(req)
            result = self.db.GetFindings(flt)
            resp.media = result
            resp.status = falcon.HTTP_200
        except Exception as ex:
            log.error(ex)
            resp.status = falcon.HTTP_500
            resp.media = {'error': str(ex)}

    def on_get_uuid(self, req, resp, entity_id):
        """Handle ``GET /findings/{entity_id}`` -- retrieve a single finding.

        Parameters
        ----------
        req : falcon.Request
            The incoming request.
        resp : falcon.Response
            On success, ``resp.media`` is the finding dict.
        entity_id : str
            UUID of the finding.

        Response Codes
        --------------
        * **200** -- finding found.
        * **404** -- finding not found.
        * **500** -- unexpected server error.
        """
        log = logging.getLogger(__name__)
        try:
            result = self.db.GetFinding(entity_id)
            if result:
                resp.media = result
                resp.status = falcon.HTTP_200
            else:
                resp.status = falcon.HTTP_404
                resp.media = {'error': 'Finding not found'}
        except Exception as ex:
            log.error(ex)
            resp.status = falcon.HTTP_500
            resp.media = {'error': str(ex)}

    def on_post_uuid(self, req, resp, entity_id):
        """Handle ``POST /findings/{entity_id}`` -- review a finding.

        Allows a clinician to mark a finding as reviewed and optionally
        attach review notes.  Delegates to ``db.ReviewFinding``.

        Parameters
        ----------
        req : falcon.Request
            JSON body with review data (e.g. ``reviewed``, ``notes``).
        resp : falcon.Response
            On success, ``resp.media`` is the updated finding dict.
        entity_id : str
            UUID of the finding to review.

        Response Codes
        --------------
        * **200** -- finding reviewed successfully.
        * **400** -- database validation error.
        * **500** -- unexpected server error.
        """
        log = logging.getLogger(__name__)
        try:
            data = self.read_body(req)
            data['id'] = entity_id
            user_id = self.get_user_id(req)
            result = self.db.ReviewFinding(user_id, data)
            resp.media = result
            resp.status = falcon.HTTP_200
        except DBException as ex:
            log.error(ex)
            resp.status = falcon.HTTP_400
            resp.media = {'error': str(ex)}
        except Exception as ex:
            log.error(ex)
            resp.status = falcon.HTTP_500
            resp.media = {'error': str(ex)}
